name: Pinchflat
version: 2025.9.26.06
slug: pinchflat
description: Pinchflat App
url: "https://github.com/Croydon/ha-apps"
webui: http://[HOST]:[PORT:8945]
arch:
  - aarch64
init: false
map:
  - type: share
    read_only: false
  - type: media
    read_only: false
    path: /downloads
  - type: addon_config
    read_only: false
    path: /config
options:
  TZ: "Europe/Berlin"
  BASIC_AUTH_USERNAME: ""
  BASIC_AUTH_PASSWORD: ""
schema:
  TZ: str
  BASIC_AUTH_USERNAME: str
  BASIC_AUTH_PASSWORD: str
video: true
ports:
  8945/tcp: 8945
ports_description:
  8945/tcp: Pinchflat web interface
